### PR TITLE
Use Align instead of SizeTransition to demonstrate AnimatedWidget more

### PR DESCRIPTION
**Pull request by collinjackson**
I think doing it this way will make it easier for people to experiment with their own animations like Opacity and Transform

### CODE REVIEW

**Comment by collinjackson** [comment]
@abarth

**Comment by abarth** [comment]
LGTM

**Comment by abarth** [comment]
Don't you need a clip?

**Comment by collinjackson** [comment]
it works without a clip because we're in a Block

**Comment by collinjackson** [comment]
I've rewritten this to use a Transition

**Comment by abarth** [comment]
LGTM

**Pull request merged**
